package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AreaDeEstudio generated by hbm2java
 */
@Entity
@Table(name="AREA_DE_ESTUDIO"
    ,schema="BOLSA_TRABAJO"
)
public class AreaDeEstudio  implements java.io.Serializable {


     private BigDecimal idAreaEstudio;
     private String nombreAreaEstudio;
     private Set<Formacion> formacions = new HashSet<Formacion>(0);
     private Set<Oferta> ofertas = new HashSet<Oferta>(0);

    public AreaDeEstudio() {
    }

	
    public AreaDeEstudio(BigDecimal idAreaEstudio) {
        this.idAreaEstudio = idAreaEstudio;
    }
    public AreaDeEstudio(BigDecimal idAreaEstudio, String nombreAreaEstudio, Set<Formacion> formacions, Set<Oferta> ofertas) {
       this.idAreaEstudio = idAreaEstudio;
       this.nombreAreaEstudio = nombreAreaEstudio;
       this.formacions = formacions;
       this.ofertas = ofertas;
    }
   
     @Id 

    
    @Column(name="ID_AREA_ESTUDIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdAreaEstudio() {
        return this.idAreaEstudio;
    }
    
    public void setIdAreaEstudio(BigDecimal idAreaEstudio) {
        this.idAreaEstudio = idAreaEstudio;
    }

    
    @Column(name="NOMBRE_AREA_ESTUDIO", length=100)
    public String getNombreAreaEstudio() {
        return this.nombreAreaEstudio;
    }
    
    public void setNombreAreaEstudio(String nombreAreaEstudio) {
        this.nombreAreaEstudio = nombreAreaEstudio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaDeEstudio")
    public Set<Formacion> getFormacions() {
        return this.formacions;
    }
    
    public void setFormacions(Set<Formacion> formacions) {
        this.formacions = formacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaDeEstudio")
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }




}


