package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AreaEmpresa generated by hbm2java
 */
@Entity
@Table(name="AREA_EMPRESA"
    ,schema="BOLSA_TRABAJO"
)
public class AreaEmpresa  implements java.io.Serializable {


     private BigDecimal idAreaEmp;
     private String nombreAreaEmp;
     private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(0);

    public AreaEmpresa() {
    }

	
    public AreaEmpresa(BigDecimal idAreaEmp) {
        this.idAreaEmp = idAreaEmp;
    }
    public AreaEmpresa(BigDecimal idAreaEmp, String nombreAreaEmp, Set<ExperienciaLaboral> experienciaLaborals) {
       this.idAreaEmp = idAreaEmp;
       this.nombreAreaEmp = nombreAreaEmp;
       this.experienciaLaborals = experienciaLaborals;
    }
   
     @Id 

    
    @Column(name="ID_AREA_EMP", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdAreaEmp() {
        return this.idAreaEmp;
    }
    
    public void setIdAreaEmp(BigDecimal idAreaEmp) {
        this.idAreaEmp = idAreaEmp;
    }

    
    @Column(name="NOMBRE_AREA_EMP", length=400)
    public String getNombreAreaEmp() {
        return this.nombreAreaEmp;
    }
    
    public void setNombreAreaEmp(String nombreAreaEmp) {
        this.nombreAreaEmp = nombreAreaEmp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaEmpresa")
    public Set<ExperienciaLaboral> getExperienciaLaborals() {
        return this.experienciaLaborals;
    }
    
    public void setExperienciaLaborals(Set<ExperienciaLaboral> experienciaLaborals) {
        this.experienciaLaborals = experienciaLaborals;
    }




}


