package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name="ARTICULO"
    ,schema="BOLSA_TRABAJO"
)
public class Articulo  implements java.io.Serializable {


     private BigDecimal idArticulo;
     private Candidato candidato;
     private String nombreArticulo;
     private String lugarPublicado;
     private Date fechaPublicacion;
     private BigDecimal numEdicion;

    public Articulo() {
    }

	
    public Articulo(BigDecimal idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Articulo(BigDecimal idArticulo, Candidato candidato, String nombreArticulo, String lugarPublicado, Date fechaPublicacion, BigDecimal numEdicion) {
       this.idArticulo = idArticulo;
       this.candidato = candidato;
       this.nombreArticulo = nombreArticulo;
       this.lugarPublicado = lugarPublicado;
       this.fechaPublicacion = fechaPublicacion;
       this.numEdicion = numEdicion;
    }
   
     @Id 

    
    @Column(name="ID_ARTICULO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(BigDecimal idArticulo) {
        this.idArticulo = idArticulo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POST_DOC")
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

    
    @Column(name="NOMBRE_ARTICULO", length=400)
    public String getNombreArticulo() {
        return this.nombreArticulo;
    }
    
    public void setNombreArticulo(String nombreArticulo) {
        this.nombreArticulo = nombreArticulo;
    }

    
    @Column(name="LUGAR_PUBLICADO", length=400)
    public String getLugarPublicado() {
        return this.lugarPublicado;
    }
    
    public void setLugarPublicado(String lugarPublicado) {
        this.lugarPublicado = lugarPublicado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_PUBLICACION", length=7)
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }

    
    @Column(name="NUM_EDICION", precision=22, scale=0)
    public BigDecimal getNumEdicion() {
        return this.numEdicion;
    }
    
    public void setNumEdicion(BigDecimal numEdicion) {
        this.numEdicion = numEdicion;
    }




}


