package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Aspirante generated by hbm2java
 */
@Entity
@Table(name="ASPIRANTE"
    ,schema="BOLSA_TRABAJO"
)
public class Aspirante  implements java.io.Serializable {


     private AspiranteId id;
     private Candidato candidato;
     private Oferta oferta;
     private BigDecimal porcentaje;

    public Aspirante() {
    }

	
    public Aspirante(AspiranteId id, Candidato candidato, Oferta oferta) {
        this.id = id;
        this.candidato = candidato;
        this.oferta = oferta;
    }
    public Aspirante(AspiranteId id, Candidato candidato, Oferta oferta, BigDecimal porcentaje) {
       this.id = id;
       this.candidato = candidato;
       this.oferta = oferta;
       this.porcentaje = porcentaje;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nit", column=@Column(name="NIT", nullable=false, length=100) ), 
        @AttributeOverride(name="idPostDoc", column=@Column(name="ID_POST_DOC", nullable=false, length=200) ) } )
    public AspiranteId getId() {
        return this.id;
    }
    
    public void setId(AspiranteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POST_DOC", nullable=false, insertable=false, updatable=false)
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_OFERTA", referencedColumnName="ID_OFERTA", insertable=false, updatable=false), 
        @JoinColumn(name="NIT", referencedColumnName="NIT", nullable=false, insertable=false, updatable=false) } )
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

    
    @Column(name="PORCENTAJE", precision=3)
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }




}


