package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AspiranteId generated by hbm2java
 */
@Embeddable
public class AspiranteId  implements java.io.Serializable {


     private String nit;
     private String idPostDoc;

    public AspiranteId() {
    }

    public AspiranteId(String nit, String idPostDoc) {
       this.nit = nit;
       this.idPostDoc = idPostDoc;
    }
   


    @Column(name="NIT", nullable=false, length=100)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }


    @Column(name="ID_POST_DOC", nullable=false, length=200)
    public String getIdPostDoc() {
        return this.idPostDoc;
    }
    
    public void setIdPostDoc(String idPostDoc) {
        this.idPostDoc = idPostDoc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AspiranteId) ) return false;
		 AspiranteId castOther = ( AspiranteId ) other; 
         
		 return ( (this.getNit()==castOther.getNit()) || ( this.getNit()!=null && castOther.getNit()!=null && this.getNit().equals(castOther.getNit()) ) )
 && ( (this.getIdPostDoc()==castOther.getIdPostDoc()) || ( this.getIdPostDoc()!=null && castOther.getIdPostDoc()!=null && this.getIdPostDoc().equals(castOther.getIdPostDoc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNit() == null ? 0 : this.getNit().hashCode() );
         result = 37 * result + ( getIdPostDoc() == null ? 0 : this.getIdPostDoc().hashCode() );
         return result;
   }   


}


