package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AspiranteId generated by hbm2java
 */
@Embeddable
public class AspiranteId  implements java.io.Serializable {


     private String idPostDoc;
     private BigDecimal idOferta;

    public AspiranteId() {
    }

    public AspiranteId(String idPostDoc, BigDecimal idOferta) {
       this.idPostDoc = idPostDoc;
       this.idOferta = idOferta;
    }
   


    @Column(name="ID_POST_DOC", nullable=false, length=200)
    public String getIdPostDoc() {
        return this.idPostDoc;
    }
    
    public void setIdPostDoc(String idPostDoc) {
        this.idPostDoc = idPostDoc;
    }


    @Column(name="ID_OFERTA", nullable=false, precision=22, scale=0)
    public BigDecimal getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(BigDecimal idOferta) {
        this.idOferta = idOferta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AspiranteId) ) return false;
		 AspiranteId castOther = ( AspiranteId ) other; 
         
		 return ( (this.getIdPostDoc()==castOther.getIdPostDoc()) || ( this.getIdPostDoc()!=null && castOther.getIdPostDoc()!=null && this.getIdPostDoc().equals(castOther.getIdPostDoc()) ) )
 && ( (this.getIdOferta()==castOther.getIdOferta()) || ( this.getIdOferta()!=null && castOther.getIdOferta()!=null && this.getIdOferta().equals(castOther.getIdOferta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPostDoc() == null ? 0 : this.getIdPostDoc().hashCode() );
         result = 37 * result + ( getIdOferta() == null ? 0 : this.getIdOferta().hashCode() );
         return result;
   }   


}


