package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Candidato generated by hbm2java
 */
@Entity
@Table(name="CANDIDATO"
    ,schema="BOLSA_TRABAJO"
)
public class Candidato  implements java.io.Serializable {


     private String idPostDoc;
     private Municipio municipio;
     private Usuarios usuarios;
     private Genero genero;
     private String primerNombre;
     private String segundoNombre;
     private String tercerNombre;
     private String primerApellido;
     private String segundoApellido;
     private String casadaApellido;
     private String direccion;
     private String email;
     private Set<Aspirante> aspirantes = new HashSet<Aspirante>(0);
     private Set<Articulo> articulos = new HashSet<Articulo>(0);
     private Set<Formacion> formacions = new HashSet<Formacion>(0);
     private Set<Logros> logroses = new HashSet<Logros>(0);
     private Set<Congresos> congresoses = new HashSet<Congresos>(0);
     private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(0);
     private Set<Ofimatica> ofimaticas = new HashSet<Ofimatica>(0);
     private Set<DetalleIdioma> detalleIdiomas = new HashSet<DetalleIdioma>(0);
     private Set<Recomendaciones> recomendacioneses = new HashSet<Recomendaciones>(0);
     private Set<Telefono> telefonos = new HashSet<Telefono>(0);

    public Candidato() {
    }

	
    public Candidato(String idPostDoc) {
        this.idPostDoc = idPostDoc;
    }
    public Candidato(String idPostDoc, Municipio municipio, Usuarios usuarios, Genero genero, String primerNombre, String segundoNombre, String tercerNombre, String primerApellido, String segundoApellido, String casadaApellido, String direccion, String email, Set<Aspirante> aspirantes, Set<Articulo> articulos, Set<Formacion> formacions, Set<Logros> logroses, Set<Congresos> congresoses, Set<ExperienciaLaboral> experienciaLaborals, Set<Ofimatica> ofimaticas, Set<DetalleIdioma> detalleIdiomas, Set<Recomendaciones> recomendacioneses, Set<Telefono> telefonos) {
       this.idPostDoc = idPostDoc;
       this.municipio = municipio;
       this.usuarios = usuarios;
       this.genero = genero;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.tercerNombre = tercerNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.casadaApellido = casadaApellido;
       this.direccion = direccion;
       this.email = email;
       this.aspirantes = aspirantes;
       this.articulos = articulos;
       this.formacions = formacions;
       this.logroses = logroses;
       this.congresoses = congresoses;
       this.experienciaLaborals = experienciaLaborals;
       this.ofimaticas = ofimaticas;
       this.detalleIdiomas = detalleIdiomas;
       this.recomendacioneses = recomendacioneses;
       this.telefonos = telefonos;
    }
   
     @Id 

    
    @Column(name="ID_POST_DOC", unique=true, nullable=false, length=200)
    public String getIdPostDoc() {
        return this.idPostDoc;
    }
    
    public void setIdPostDoc(String idPostDoc) {
        this.idPostDoc = idPostDoc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_MUNI", referencedColumnName="ID_MUNI"), 
        @JoinColumn(name="ID_DEPTO", referencedColumnName="ID_DEPTO") } )
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_GENERO")
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    
    @Column(name="PRIMER_NOMBRE", length=200)
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    
    @Column(name="SEGUNDO_NOMBRE", length=200)
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    
    @Column(name="TERCER_NOMBRE", length=200)
    public String getTercerNombre() {
        return this.tercerNombre;
    }
    
    public void setTercerNombre(String tercerNombre) {
        this.tercerNombre = tercerNombre;
    }

    
    @Column(name="PRIMER_APELLIDO", length=200)
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    
    @Column(name="SEGUNDO_APELLIDO", length=200)
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    
    @Column(name="CASADA_APELLIDO", length=200)
    public String getCasadaApellido() {
        return this.casadaApellido;
    }
    
    public void setCasadaApellido(String casadaApellido) {
        this.casadaApellido = casadaApellido;
    }

    
    @Column(name="DIRECCION", length=200)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="EMAIL", length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<Aspirante> getAspirantes() {
        return this.aspirantes;
    }
    
    public void setAspirantes(Set<Aspirante> aspirantes) {
        this.aspirantes = aspirantes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<Articulo> getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set<Articulo> articulos) {
        this.articulos = articulos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<Formacion> getFormacions() {
        return this.formacions;
    }
    
    public void setFormacions(Set<Formacion> formacions) {
        this.formacions = formacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<Logros> getLogroses() {
        return this.logroses;
    }
    
    public void setLogroses(Set<Logros> logroses) {
        this.logroses = logroses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<Congresos> getCongresoses() {
        return this.congresoses;
    }
    
    public void setCongresoses(Set<Congresos> congresoses) {
        this.congresoses = congresoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<ExperienciaLaboral> getExperienciaLaborals() {
        return this.experienciaLaborals;
    }
    
    public void setExperienciaLaborals(Set<ExperienciaLaboral> experienciaLaborals) {
        this.experienciaLaborals = experienciaLaborals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<Ofimatica> getOfimaticas() {
        return this.ofimaticas;
    }
    
    public void setOfimaticas(Set<Ofimatica> ofimaticas) {
        this.ofimaticas = ofimaticas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<DetalleIdioma> getDetalleIdiomas() {
        return this.detalleIdiomas;
    }
    
    public void setDetalleIdiomas(Set<DetalleIdioma> detalleIdiomas) {
        this.detalleIdiomas = detalleIdiomas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<Recomendaciones> getRecomendacioneses() {
        return this.recomendacioneses;
    }
    
    public void setRecomendacioneses(Set<Recomendaciones> recomendacioneses) {
        this.recomendacioneses = recomendacioneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidato")
    public Set<Telefono> getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }




}


