package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="DEPARTAMENTO"
    ,schema="BOLSA_TRABAJO"
)
public class Departamento  implements java.io.Serializable {


     private BigDecimal idDepto;
     private String nombreDepto;
     private Set<Municipio> municipios = new HashSet<Municipio>(0);

    public Departamento() {
    }

	
    public Departamento(BigDecimal idDepto) {
        this.idDepto = idDepto;
    }
    public Departamento(BigDecimal idDepto, String nombreDepto, Set<Municipio> municipios) {
       this.idDepto = idDepto;
       this.nombreDepto = nombreDepto;
       this.municipios = municipios;
    }
   
     @Id 

    
    @Column(name="ID_DEPTO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdDepto() {
        return this.idDepto;
    }
    
    public void setIdDepto(BigDecimal idDepto) {
        this.idDepto = idDepto;
    }

    
    @Column(name="NOMBRE_DEPTO", length=100)
    public String getNombreDepto() {
        return this.nombreDepto;
    }
    
    public void setNombreDepto(String nombreDepto) {
        this.nombreDepto = nombreDepto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


