package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleIdioma generated by hbm2java
 */
@Entity
@Table(name="DETALLE_IDIOMA"
    ,schema="BOLSA_TRABAJO"
)
public class DetalleIdioma  implements java.io.Serializable {


     private DetalleIdiomaId id;
     private Candidato candidato;
     private Idioma idioma;
     private NivelIdioma nivelIdioma;

    public DetalleIdioma() {
    }

	
    public DetalleIdioma(DetalleIdiomaId id, Candidato candidato, Idioma idioma) {
        this.id = id;
        this.candidato = candidato;
        this.idioma = idioma;
    }
    public DetalleIdioma(DetalleIdiomaId id, Candidato candidato, Idioma idioma, NivelIdioma nivelIdioma) {
       this.id = id;
       this.candidato = candidato;
       this.idioma = idioma;
       this.nivelIdioma = nivelIdioma;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idIdioma", column=@Column(name="ID_IDIOMA", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="idPostDoc", column=@Column(name="ID_POST_DOC", nullable=false, length=200) ) } )
    public DetalleIdiomaId getId() {
        return this.id;
    }
    
    public void setId(DetalleIdiomaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POST_DOC", nullable=false, insertable=false, updatable=false)
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_IDIOMA", nullable=false, insertable=false, updatable=false)
    public Idioma getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_NIVEL")
    public NivelIdioma getNivelIdioma() {
        return this.nivelIdioma;
    }
    
    public void setNivelIdioma(NivelIdioma nivelIdioma) {
        this.nivelIdioma = nivelIdioma;
    }




}


