package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="EMPRESA"
    ,schema="BOLSA_TRABAJO"
)
public class Empresa  implements java.io.Serializable {


     private String nit;
     private GiroEmpresa giroEmpresa;
     private Municipio municipio;
     private Reclutador reclutador;
     private TipoEmpresa tipoEmpresa;
     private Usuarios usuarios;
     private String razonSocial;
     private String nombreComercial;
     private String ubicacion;
     private String descripcion;
     private String paginaWeb;
     private String email;
     private Set<Oferta> ofertas = new HashSet<Oferta>(0);

    public Empresa() {
    }

	
    public Empresa(String nit) {
        this.nit = nit;
    }
    public Empresa(String nit, GiroEmpresa giroEmpresa, Municipio municipio, Reclutador reclutador, TipoEmpresa tipoEmpresa, Usuarios usuarios, String razonSocial, String nombreComercial, String ubicacion, String descripcion, String paginaWeb, String email, Set<Oferta> ofertas) {
       this.nit = nit;
       this.giroEmpresa = giroEmpresa;
       this.municipio = municipio;
       this.reclutador = reclutador;
       this.tipoEmpresa = tipoEmpresa;
       this.usuarios = usuarios;
       this.razonSocial = razonSocial;
       this.nombreComercial = nombreComercial;
       this.ubicacion = ubicacion;
       this.descripcion = descripcion;
       this.paginaWeb = paginaWeb;
       this.email = email;
       this.ofertas = ofertas;
    }
   
     @Id 

    
    @Column(name="NIT", unique=true, nullable=false, length=100)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_GIRO")
    public GiroEmpresa getGiroEmpresa() {
        return this.giroEmpresa;
    }
    
    public void setGiroEmpresa(GiroEmpresa giroEmpresa) {
        this.giroEmpresa = giroEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_MUNI", referencedColumnName="ID_MUNI"), 
        @JoinColumn(name="ID_DEPTO", referencedColumnName="ID_DEPTO") } )
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DUI")
    public Reclutador getReclutador() {
        return this.reclutador;
    }
    
    public void setReclutador(Reclutador reclutador) {
        this.reclutador = reclutador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_EMP")
    public TipoEmpresa getTipoEmpresa() {
        return this.tipoEmpresa;
    }
    
    public void setTipoEmpresa(TipoEmpresa tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="RAZON_SOCIAL", length=1020)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="NOMBRE_COMERCIAL", length=1020)
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }

    
    @Column(name="UBICACION", length=4000)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="DESCRIPCION", length=4000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="PAGINA_WEB", length=1020)
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }

    
    @Column(name="EMAIL", length=1020)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }




}


