package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoFormacion generated by hbm2java
 */
@Entity
@Table(name="ESTADO_FORMACION"
    ,schema="BOLSA_TRABAJO"
)
public class EstadoFormacion  implements java.io.Serializable {


     private BigDecimal idEstadoForm;
     private String nombreEstado;
     private Set<Formacion> formacions = new HashSet<Formacion>(0);

    public EstadoFormacion() {
    }

	
    public EstadoFormacion(BigDecimal idEstadoForm) {
        this.idEstadoForm = idEstadoForm;
    }
    public EstadoFormacion(BigDecimal idEstadoForm, String nombreEstado, Set<Formacion> formacions) {
       this.idEstadoForm = idEstadoForm;
       this.nombreEstado = nombreEstado;
       this.formacions = formacions;
    }
   
     @Id 

    
    @Column(name="ID_ESTADO_FORM", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdEstadoForm() {
        return this.idEstadoForm;
    }
    
    public void setIdEstadoForm(BigDecimal idEstadoForm) {
        this.idEstadoForm = idEstadoForm;
    }

    
    @Column(name="NOMBRE_ESTADO", length=60)
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoFormacion")
    public Set<Formacion> getFormacions() {
        return this.formacions;
    }
    
    public void setFormacions(Set<Formacion> formacions) {
        this.formacions = formacions;
    }




}


