package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name="EXAMEN"
    ,schema="BOLSA_TRABAJO"
)
public class Examen  implements java.io.Serializable {


     private BigDecimal idExamen;
     private Oferta oferta;
     private Reclutador reclutador;
     private TipoExamen tipoExamen;
     private BigDecimal puntuacion;
     private Set<Preguntas> preguntases = new HashSet<Preguntas>(0);

    public Examen() {
    }

	
    public Examen(BigDecimal idExamen) {
        this.idExamen = idExamen;
    }
    public Examen(BigDecimal idExamen, Oferta oferta, Reclutador reclutador, TipoExamen tipoExamen, BigDecimal puntuacion, Set<Preguntas> preguntases) {
       this.idExamen = idExamen;
       this.oferta = oferta;
       this.reclutador = reclutador;
       this.tipoExamen = tipoExamen;
       this.puntuacion = puntuacion;
       this.preguntases = preguntases;
    }
   
     @Id 

    
    @Column(name="ID_EXAMEN", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(BigDecimal idExamen) {
        this.idExamen = idExamen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_OFERTA", referencedColumnName="ID_OFERTA"), 
        @JoinColumn(name="NIT", referencedColumnName="NIT") } )
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DUI")
    public Reclutador getReclutador() {
        return this.reclutador;
    }
    
    public void setReclutador(Reclutador reclutador) {
        this.reclutador = reclutador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_EXAMEN")
    public TipoExamen getTipoExamen() {
        return this.tipoExamen;
    }
    
    public void setTipoExamen(TipoExamen tipoExamen) {
        this.tipoExamen = tipoExamen;
    }

    
    @Column(name="PUNTUACION", precision=3)
    public BigDecimal getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(BigDecimal puntuacion) {
        this.puntuacion = puntuacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="examen")
    public Set<Preguntas> getPreguntases() {
        return this.preguntases;
    }
    
    public void setPreguntases(Set<Preguntas> preguntases) {
        this.preguntases = preguntases;
    }




}


