package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExperienciaLaboral generated by hbm2java
 */
@Entity
@Table(name="EXPERIENCIA_LABORAL"
    ,schema="BOLSA_TRABAJO"
)
public class ExperienciaLaboral  implements java.io.Serializable {


     private BigDecimal idExperiencia;
     private GiroEmpresa giroEmpresa;
     private AreaEmpresa areaEmpresa;
     private Candidato candidato;
     private String organizacion;
     private String cargoCandidato;
     private String funciones;
     private Date fechaInicio;
     private Date fechaFin;

    public ExperienciaLaboral() {
    }

	
    public ExperienciaLaboral(BigDecimal idExperiencia) {
        this.idExperiencia = idExperiencia;
    }
    public ExperienciaLaboral(BigDecimal idExperiencia, GiroEmpresa giroEmpresa, AreaEmpresa areaEmpresa, Candidato candidato, String organizacion, String cargoCandidato, String funciones, Date fechaInicio, Date fechaFin) {
       this.idExperiencia = idExperiencia;
       this.giroEmpresa = giroEmpresa;
       this.areaEmpresa = areaEmpresa;
       this.candidato = candidato;
       this.organizacion = organizacion;
       this.cargoCandidato = cargoCandidato;
       this.funciones = funciones;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
     @Id 

    
    @Column(name="ID_EXPERIENCIA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdExperiencia() {
        return this.idExperiencia;
    }
    
    public void setIdExperiencia(BigDecimal idExperiencia) {
        this.idExperiencia = idExperiencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_GIRO")
    public GiroEmpresa getGiroEmpresa() {
        return this.giroEmpresa;
    }
    
    public void setGiroEmpresa(GiroEmpresa giroEmpresa) {
        this.giroEmpresa = giroEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_AREA")
    public AreaEmpresa getAreaEmpresa() {
        return this.areaEmpresa;
    }
    
    public void setAreaEmpresa(AreaEmpresa areaEmpresa) {
        this.areaEmpresa = areaEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POST_DOC")
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

    
    @Column(name="ORGANIZACION", length=400)
    public String getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(String organizacion) {
        this.organizacion = organizacion;
    }

    
    @Column(name="CARGO_CANDIDATO", length=1020)
    public String getCargoCandidato() {
        return this.cargoCandidato;
    }
    
    public void setCargoCandidato(String cargoCandidato) {
        this.cargoCandidato = cargoCandidato;
    }

    
    @Column(name="FUNCIONES", length=4000)
    public String getFunciones() {
        return this.funciones;
    }
    
    public void setFunciones(String funciones) {
        this.funciones = funciones;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", length=7)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FIN", length=7)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


