package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formacion generated by hbm2java
 */
@Entity
@Table(name="FORMACION"
    ,schema="BOLSA_TRABAJO"
)
public class Formacion  implements java.io.Serializable {


     private BigDecimal idFormacion;
     private NivelEstudio nivelEstudio;
     private AreaDeEstudio areaDeEstudio;
     private Candidato candidato;
     private EstadoFormacion estadoFormacion;
     private String nombreCentro;
     private Date fechaInicio;
     private Date fechaFin;

    public Formacion() {
    }

	
    public Formacion(BigDecimal idFormacion) {
        this.idFormacion = idFormacion;
    }
    public Formacion(BigDecimal idFormacion, NivelEstudio nivelEstudio, AreaDeEstudio areaDeEstudio, Candidato candidato, EstadoFormacion estadoFormacion, String nombreCentro, Date fechaInicio, Date fechaFin) {
       this.idFormacion = idFormacion;
       this.nivelEstudio = nivelEstudio;
       this.areaDeEstudio = areaDeEstudio;
       this.candidato = candidato;
       this.estadoFormacion = estadoFormacion;
       this.nombreCentro = nombreCentro;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
     @Id 

    
    @Column(name="ID_FORMACION", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdFormacion() {
        return this.idFormacion;
    }
    
    public void setIdFormacion(BigDecimal idFormacion) {
        this.idFormacion = idFormacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_NIVEL")
    public NivelEstudio getNivelEstudio() {
        return this.nivelEstudio;
    }
    
    public void setNivelEstudio(NivelEstudio nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_AREA")
    public AreaDeEstudio getAreaDeEstudio() {
        return this.areaDeEstudio;
    }
    
    public void setAreaDeEstudio(AreaDeEstudio areaDeEstudio) {
        this.areaDeEstudio = areaDeEstudio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POST_DOC")
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ESTADO_FORM")
    public EstadoFormacion getEstadoFormacion() {
        return this.estadoFormacion;
    }
    
    public void setEstadoFormacion(EstadoFormacion estadoFormacion) {
        this.estadoFormacion = estadoFormacion;
    }

    
    @Column(name="NOMBRE_CENTRO", length=200)
    public String getNombreCentro() {
        return this.nombreCentro;
    }
    
    public void setNombreCentro(String nombreCentro) {
        this.nombreCentro = nombreCentro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", length=7)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FIN", length=7)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


