package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name="GENERO"
    ,schema="BOLSA_TRABAJO"
)
public class Genero  implements java.io.Serializable {


     private BigDecimal idGenero;
     private String nombreGenero;
     private Set<Candidato> candidatos = new HashSet<Candidato>(0);

    public Genero() {
    }

	
    public Genero(BigDecimal idGenero) {
        this.idGenero = idGenero;
    }
    public Genero(BigDecimal idGenero, String nombreGenero, Set<Candidato> candidatos) {
       this.idGenero = idGenero;
       this.nombreGenero = nombreGenero;
       this.candidatos = candidatos;
    }
   
     @Id 

    
    @Column(name="ID_GENERO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(BigDecimal idGenero) {
        this.idGenero = idGenero;
    }

    
    @Column(name="NOMBRE_GENERO", length=400)
    public String getNombreGenero() {
        return this.nombreGenero;
    }
    
    public void setNombreGenero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="genero")
    public Set<Candidato> getCandidatos() {
        return this.candidatos;
    }
    
    public void setCandidatos(Set<Candidato> candidatos) {
        this.candidatos = candidatos;
    }




}


