package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Idioma generated by hbm2java
 */
@Entity
@Table(name="IDIOMA"
    ,schema="BOLSA_TRABAJO"
)
public class Idioma  implements java.io.Serializable {


     private BigDecimal idIdioma;
     private String nombreIdioma;
     private Set<DetalleIdioma> detalleIdiomas = new HashSet<DetalleIdioma>(0);

    public Idioma() {
    }

	
    public Idioma(BigDecimal idIdioma) {
        this.idIdioma = idIdioma;
    }
    public Idioma(BigDecimal idIdioma, String nombreIdioma, Set<DetalleIdioma> detalleIdiomas) {
       this.idIdioma = idIdioma;
       this.nombreIdioma = nombreIdioma;
       this.detalleIdiomas = detalleIdiomas;
    }
   
     @Id 

    
    @Column(name="ID_IDIOMA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdIdioma() {
        return this.idIdioma;
    }
    
    public void setIdIdioma(BigDecimal idIdioma) {
        this.idIdioma = idIdioma;
    }

    
    @Column(name="NOMBRE_IDIOMA", length=200)
    public String getNombreIdioma() {
        return this.nombreIdioma;
    }
    
    public void setNombreIdioma(String nombreIdioma) {
        this.nombreIdioma = nombreIdioma;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="idioma")
    public Set<DetalleIdioma> getDetalleIdiomas() {
        return this.detalleIdiomas;
    }
    
    public void setDetalleIdiomas(Set<DetalleIdioma> detalleIdiomas) {
        this.detalleIdiomas = detalleIdiomas;
    }




}


