package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logros generated by hbm2java
 */
@Entity
@Table(name="LOGROS"
    ,schema="BOLSA_TRABAJO"
)
public class Logros  implements java.io.Serializable {


     private BigDecimal idLogros;
     private Candidato candidato;
     private String lugar;
     private Date fecha;

    public Logros() {
    }

	
    public Logros(BigDecimal idLogros) {
        this.idLogros = idLogros;
    }
    public Logros(BigDecimal idLogros, Candidato candidato, String lugar, Date fecha) {
       this.idLogros = idLogros;
       this.candidato = candidato;
       this.lugar = lugar;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="ID_LOGROS", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdLogros() {
        return this.idLogros;
    }
    
    public void setIdLogros(BigDecimal idLogros) {
        this.idLogros = idLogros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POST_DOC")
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

    
    @Column(name="LUGAR", length=400)
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


