package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logs generated by hbm2java
 */
@Entity
@Table(name="LOGS"
    ,schema="BOLSA_TRABAJO"
)
public class Logs  implements java.io.Serializable {


     private BigDecimal idLog;
     private String idUsuario;
     private String nombreUsuario;
     private Date fechaIn;

    public Logs() {
    }

	
    public Logs(BigDecimal idLog) {
        this.idLog = idLog;
    }
    public Logs(BigDecimal idLog, String idUsuario, String nombreUsuario, Date fechaIn) {
       this.idLog = idLog;
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.fechaIn = fechaIn;
    }
   
     @Id 

    
    @Column(name="ID_LOG", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(BigDecimal idLog) {
        this.idLog = idLog;
    }

    
    @Column(name="ID_USUARIO", length=200)
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="NOMBRE_USUARIO", length=1020)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_IN", length=7)
    public Date getFechaIn() {
        return this.fechaIn;
    }
    
    public void setFechaIn(Date fechaIn) {
        this.fechaIn = fechaIn;
    }




}


