package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MunicipioId generated by hbm2java
 */
@Embeddable
public class MunicipioId  implements java.io.Serializable {


     private BigDecimal idMuni;
     private BigDecimal idDepto;

    public MunicipioId() {
    }

    public MunicipioId(BigDecimal idMuni, BigDecimal idDepto) {
       this.idMuni = idMuni;
       this.idDepto = idDepto;
    }
   


    @Column(name="ID_MUNI", nullable=false, precision=22, scale=0)
    public BigDecimal getIdMuni() {
        return this.idMuni;
    }
    
    public void setIdMuni(BigDecimal idMuni) {
        this.idMuni = idMuni;
    }


    @Column(name="ID_DEPTO", nullable=false, precision=22, scale=0)
    public BigDecimal getIdDepto() {
        return this.idDepto;
    }
    
    public void setIdDepto(BigDecimal idDepto) {
        this.idDepto = idDepto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MunicipioId) ) return false;
		 MunicipioId castOther = ( MunicipioId ) other; 
         
		 return ( (this.getIdMuni()==castOther.getIdMuni()) || ( this.getIdMuni()!=null && castOther.getIdMuni()!=null && this.getIdMuni().equals(castOther.getIdMuni()) ) )
 && ( (this.getIdDepto()==castOther.getIdDepto()) || ( this.getIdDepto()!=null && castOther.getIdDepto()!=null && this.getIdDepto().equals(castOther.getIdDepto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdMuni() == null ? 0 : this.getIdMuni().hashCode() );
         result = 37 * result + ( getIdDepto() == null ? 0 : this.getIdDepto().hashCode() );
         return result;
   }   


}


