package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name="MUNICIPIO"
    ,schema="BOLSA_TRABAJO"
)
public class Municipio  implements java.io.Serializable {


     private MunicipioId id;
     private Departamento departamento;
     private String nombreMuni;
     private Set<Empresa> empresas = new HashSet<Empresa>(0);
     private Set<Candidato> candidatos = new HashSet<Candidato>(0);

    public Municipio() {
    }

	
    public Municipio(MunicipioId id, Departamento departamento) {
        this.id = id;
        this.departamento = departamento;
    }
    public Municipio(MunicipioId id, Departamento departamento, String nombreMuni, Set<Empresa> empresas, Set<Candidato> candidatos) {
       this.id = id;
       this.departamento = departamento;
       this.nombreMuni = nombreMuni;
       this.empresas = empresas;
       this.candidatos = candidatos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idMuni", column=@Column(name="ID_MUNI", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="idDepto", column=@Column(name="ID_DEPTO", nullable=false, precision=22, scale=0) ) } )
    public MunicipioId getId() {
        return this.id;
    }
    
    public void setId(MunicipioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DEPTO", nullable=false, insertable=false, updatable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="NOMBRE_MUNI", length=200)
    public String getNombreMuni() {
        return this.nombreMuni;
    }
    
    public void setNombreMuni(String nombreMuni) {
        this.nombreMuni = nombreMuni;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="municipio")
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="municipio")
    public Set<Candidato> getCandidatos() {
        return this.candidatos;
    }
    
    public void setCandidatos(Set<Candidato> candidatos) {
        this.candidatos = candidatos;
    }




}


