package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NivelIdioma generated by hbm2java
 */
@Entity
@Table(name="NIVEL_IDIOMA"
    ,schema="BOLSA_TRABAJO"
)
public class NivelIdioma  implements java.io.Serializable {


     private BigDecimal idNivel;
     private String nombreNivel;
     private Set<DetalleIdioma> detalleIdiomas = new HashSet<DetalleIdioma>(0);

    public NivelIdioma() {
    }

	
    public NivelIdioma(BigDecimal idNivel) {
        this.idNivel = idNivel;
    }
    public NivelIdioma(BigDecimal idNivel, String nombreNivel, Set<DetalleIdioma> detalleIdiomas) {
       this.idNivel = idNivel;
       this.nombreNivel = nombreNivel;
       this.detalleIdiomas = detalleIdiomas;
    }
   
     @Id 

    
    @Column(name="ID_NIVEL", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdNivel() {
        return this.idNivel;
    }
    
    public void setIdNivel(BigDecimal idNivel) {
        this.idNivel = idNivel;
    }

    
    @Column(name="NOMBRE_NIVEL", length=50)
    public String getNombreNivel() {
        return this.nombreNivel;
    }
    
    public void setNombreNivel(String nombreNivel) {
        this.nombreNivel = nombreNivel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nivelIdioma")
    public Set<DetalleIdioma> getDetalleIdiomas() {
        return this.detalleIdiomas;
    }
    
    public void setDetalleIdiomas(Set<DetalleIdioma> detalleIdiomas) {
        this.detalleIdiomas = detalleIdiomas;
    }




}


