package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NivelEstudio generated by hbm2java
 */
@Entity
@Table(name="NIVEL_ESTUDIO"
    ,schema="BOLSA_TRABAJO"
)
public class NivelEstudio  implements java.io.Serializable {


     private BigDecimal idNivelEstudio;
     private String nombreNivelEstudio;
     private Set<Formacion> formacions = new HashSet<Formacion>(0);
     private Set<Oferta> ofertas = new HashSet<Oferta>(0);

    public NivelEstudio() {
    }

	
    public NivelEstudio(BigDecimal idNivelEstudio) {
        this.idNivelEstudio = idNivelEstudio;
    }
    public NivelEstudio(BigDecimal idNivelEstudio, String nombreNivelEstudio, Set<Formacion> formacions, Set<Oferta> ofertas) {
       this.idNivelEstudio = idNivelEstudio;
       this.nombreNivelEstudio = nombreNivelEstudio;
       this.formacions = formacions;
       this.ofertas = ofertas;
    }
   
     @Id 

    
    @Column(name="ID_NIVEL_ESTUDIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdNivelEstudio() {
        return this.idNivelEstudio;
    }
    
    public void setIdNivelEstudio(BigDecimal idNivelEstudio) {
        this.idNivelEstudio = idNivelEstudio;
    }

    
    @Column(name="NOMBRE_NIVEL_ESTUDIO", length=200)
    public String getNombreNivelEstudio() {
        return this.nombreNivelEstudio;
    }
    
    public void setNombreNivelEstudio(String nombreNivelEstudio) {
        this.nombreNivelEstudio = nombreNivelEstudio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nivelEstudio")
    public Set<Formacion> getFormacions() {
        return this.formacions;
    }
    
    public void setFormacions(Set<Formacion> formacions) {
        this.formacions = formacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nivelEstudio")
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }




}


