package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OfertaId generated by hbm2java
 */
@Embeddable
public class OfertaId  implements java.io.Serializable {


     private BigDecimal idOferta;
     private String nit;

    public OfertaId() {
    }

    public OfertaId(BigDecimal idOferta, String nit) {
       this.idOferta = idOferta;
       this.nit = nit;
    }
   


    @Column(name="ID_OFERTA", nullable=false, precision=22, scale=0)
    public BigDecimal getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(BigDecimal idOferta) {
        this.idOferta = idOferta;
    }


    @Column(name="NIT", nullable=false, length=100)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfertaId) ) return false;
		 OfertaId castOther = ( OfertaId ) other; 
         
		 return ( (this.getIdOferta()==castOther.getIdOferta()) || ( this.getIdOferta()!=null && castOther.getIdOferta()!=null && this.getIdOferta().equals(castOther.getIdOferta()) ) )
 && ( (this.getNit()==castOther.getNit()) || ( this.getNit()!=null && castOther.getNit()!=null && this.getNit().equals(castOther.getNit()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdOferta() == null ? 0 : this.getIdOferta().hashCode() );
         result = 37 * result + ( getNit() == null ? 0 : this.getNit().hashCode() );
         return result;
   }   


}


