package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oferta generated by hbm2java
 */
@Entity
@Table(name="OFERTA"
    ,schema="BOLSA_TRABAJO"
)
public class Oferta  implements java.io.Serializable {


     private OfertaId id;
     private AreaDeEstudio areaDeEstudio;
     private Empresa empresa;
     private NivelEstudio nivelEstudio;
     private BigDecimal aniosExp;
     private Date fechaExpiracion;
     private String descripcion;
     private BigDecimal tieneExamen;
     private Set<Aspirante> aspirantes = new HashSet<Aspirante>(0);
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Oferta() {
    }

	
    public Oferta(OfertaId id, Empresa empresa) {
        this.id = id;
        this.empresa = empresa;
    }
    public Oferta(OfertaId id, AreaDeEstudio areaDeEstudio, Empresa empresa, NivelEstudio nivelEstudio, BigDecimal aniosExp, Date fechaExpiracion, String descripcion, BigDecimal tieneExamen, Set<Aspirante> aspirantes, Set<Examen> examens) {
       this.id = id;
       this.areaDeEstudio = areaDeEstudio;
       this.empresa = empresa;
       this.nivelEstudio = nivelEstudio;
       this.aniosExp = aniosExp;
       this.fechaExpiracion = fechaExpiracion;
       this.descripcion = descripcion;
       this.tieneExamen = tieneExamen;
       this.aspirantes = aspirantes;
       this.examens = examens;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idOferta", column=@Column(name="ID_OFERTA", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="nit", column=@Column(name="NIT", nullable=false, length=100) ) } )
    public OfertaId getId() {
        return this.id;
    }
    
    public void setId(OfertaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_AREA_ESTUDIO")
    public AreaDeEstudio getAreaDeEstudio() {
        return this.areaDeEstudio;
    }
    
    public void setAreaDeEstudio(AreaDeEstudio areaDeEstudio) {
        this.areaDeEstudio = areaDeEstudio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NIT", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_NIVEL_ESTUDIO")
    public NivelEstudio getNivelEstudio() {
        return this.nivelEstudio;
    }
    
    public void setNivelEstudio(NivelEstudio nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }

    
    @Column(name="ANIOS_EXP", precision=22, scale=0)
    public BigDecimal getAniosExp() {
        return this.aniosExp;
    }
    
    public void setAniosExp(BigDecimal aniosExp) {
        this.aniosExp = aniosExp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_EXPIRACION", length=7)
    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }

    
    @Column(name="DESCRIPCION", length=4000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="TIENE_EXAMEN", precision=22, scale=0)
    public BigDecimal getTieneExamen() {
        return this.tieneExamen;
    }
    
    public void setTieneExamen(BigDecimal tieneExamen) {
        this.tieneExamen = tieneExamen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oferta")
    public Set<Aspirante> getAspirantes() {
        return this.aspirantes;
    }
    
    public void setAspirantes(Set<Aspirante> aspirantes) {
        this.aspirantes = aspirantes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oferta")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }




}


