package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ofimatica generated by hbm2java
 */
@Entity
@Table(name="OFIMATICA"
    ,schema="BOLSA_TRABAJO"
)
public class Ofimatica  implements java.io.Serializable {


     private OfimaticaId id;
     private Candidato candidato;
     private CatalogoOfimatica catalogoOfimatica;

    public Ofimatica() {
    }

	
    public Ofimatica(OfimaticaId id) {
        this.id = id;
    }
    public Ofimatica(OfimaticaId id, Candidato candidato, CatalogoOfimatica catalogoOfimatica) {
       this.id = id;
       this.candidato = candidato;
       this.catalogoOfimatica = catalogoOfimatica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idOfimatica", column=@Column(name="ID_OFIMATICA", precision=22, scale=0) ), 
        @AttributeOverride(name="idPostDoc", column=@Column(name="ID_POST_DOC", length=200) ) } )
    public OfimaticaId getId() {
        return this.id;
    }
    
    public void setId(OfimaticaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POST_DOC", insertable=false, updatable=false)
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_OFIMATICA", insertable=false, updatable=false)
    public CatalogoOfimatica getCatalogoOfimatica() {
        return this.catalogoOfimatica;
    }
    
    public void setCatalogoOfimatica(CatalogoOfimatica catalogoOfimatica) {
        this.catalogoOfimatica = catalogoOfimatica;
    }




}


