package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Participacion generated by hbm2java
 */
@Entity
@Table(name="PARTICIPACION"
    ,schema="BOLSA_TRABAJO"
)
public class Participacion  implements java.io.Serializable {


     private BigDecimal idParticipacion;
     private String nombreParticipacion;
     private Set<Congresos> congresoses = new HashSet<Congresos>(0);

    public Participacion() {
    }

	
    public Participacion(BigDecimal idParticipacion) {
        this.idParticipacion = idParticipacion;
    }
    public Participacion(BigDecimal idParticipacion, String nombreParticipacion, Set<Congresos> congresoses) {
       this.idParticipacion = idParticipacion;
       this.nombreParticipacion = nombreParticipacion;
       this.congresoses = congresoses;
    }
   
     @Id 

    
    @Column(name="ID_PARTICIPACION", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdParticipacion() {
        return this.idParticipacion;
    }
    
    public void setIdParticipacion(BigDecimal idParticipacion) {
        this.idParticipacion = idParticipacion;
    }

    
    @Column(name="NOMBRE_PARTICIPACION", length=200)
    public String getNombreParticipacion() {
        return this.nombreParticipacion;
    }
    
    public void setNombreParticipacion(String nombreParticipacion) {
        this.nombreParticipacion = nombreParticipacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="participacion")
    public Set<Congresos> getCongresoses() {
        return this.congresoses;
    }
    
    public void setCongresoses(Set<Congresos> congresoses) {
        this.congresoses = congresoses;
    }




}


