package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reclutador generated by hbm2java
 */
@Entity
@Table(name="RECLUTADOR"
    ,schema="BOLSA_TRABAJO"
)
public class Reclutador  implements java.io.Serializable {


     private String dui;
     private String nombres;
     private String apellidos;
     private String telefono;
     private Set<Examen> examens = new HashSet<Examen>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public Reclutador() {
    }

	
    public Reclutador(String dui) {
        this.dui = dui;
    }
    public Reclutador(String dui, String nombres, String apellidos, String telefono, Set<Examen> examens, Set<Empresa> empresas) {
       this.dui = dui;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.examens = examens;
       this.empresas = empresas;
    }
   
     @Id 

    
    @Column(name="DUI", unique=true, nullable=false, length=100)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

    
    @Column(name="NOMBRES", length=400)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="APELLIDOS", length=400)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="TELEFONO", length=400)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="reclutador")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="reclutador")
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }




}


