package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="ROLES"
    ,schema="BOLSA_TRABAJO"
)
public class Roles  implements java.io.Serializable {


     private BigDecimal idRol;
     private Usuarios usuarios;
     private String nombreRol;

    public Roles() {
    }

	
    public Roles(BigDecimal idRol) {
        this.idRol = idRol;
    }
    public Roles(BigDecimal idRol, Usuarios usuarios, String nombreRol) {
       this.idRol = idRol;
       this.usuarios = usuarios;
       this.nombreRol = nombreRol;
    }
   
     @Id 

    
    @Column(name="ID_ROL", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(BigDecimal idRol) {
        this.idRol = idRol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="NOMBRE_ROL", length=200)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }




}


