package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="TELEFONO"
    ,schema="BOLSA_TRABAJO"
)
public class Telefono  implements java.io.Serializable {


     private TelefonoId id;
     private Candidato candidato;
     private TipoTelefono tipoTelefono;

    public Telefono() {
    }

	
    public Telefono(TelefonoId id) {
        this.id = id;
    }
    public Telefono(TelefonoId id, Candidato candidato, TipoTelefono tipoTelefono) {
       this.id = id;
       this.candidato = candidato;
       this.tipoTelefono = tipoTelefono;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTipo", column=@Column(name="ID_TIPO", precision=22, scale=0) ), 
        @AttributeOverride(name="idPostDoc", column=@Column(name="ID_POST_DOC", length=200) ) } )
    public TelefonoId getId() {
        return this.id;
    }
    
    public void setId(TelefonoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POST_DOC", insertable=false, updatable=false)
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO", insertable=false, updatable=false)
    public TipoTelefono getTipoTelefono() {
        return this.tipoTelefono;
    }
    
    public void setTipoTelefono(TipoTelefono tipoTelefono) {
        this.tipoTelefono = tipoTelefono;
    }




}


