package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelefonoId generated by hbm2java
 */
@Embeddable
public class TelefonoId  implements java.io.Serializable {


     private BigDecimal idTipo;
     private String idPostDoc;

    public TelefonoId() {
    }

    public TelefonoId(BigDecimal idTipo, String idPostDoc) {
       this.idTipo = idTipo;
       this.idPostDoc = idPostDoc;
    }
   


    @Column(name="ID_TIPO", precision=22, scale=0)
    public BigDecimal getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }


    @Column(name="ID_POST_DOC", length=200)
    public String getIdPostDoc() {
        return this.idPostDoc;
    }
    
    public void setIdPostDoc(String idPostDoc) {
        this.idPostDoc = idPostDoc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefonoId) ) return false;
		 TelefonoId castOther = ( TelefonoId ) other; 
         
		 return ( (this.getIdTipo()==castOther.getIdTipo()) || ( this.getIdTipo()!=null && castOther.getIdTipo()!=null && this.getIdTipo().equals(castOther.getIdTipo()) ) )
 && ( (this.getIdPostDoc()==castOther.getIdPostDoc()) || ( this.getIdPostDoc()!=null && castOther.getIdPostDoc()!=null && this.getIdPostDoc().equals(castOther.getIdPostDoc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTipo() == null ? 0 : this.getIdTipo().hashCode() );
         result = 37 * result + ( getIdPostDoc() == null ? 0 : this.getIdPostDoc().hashCode() );
         return result;
   }   


}


