package Entidad;
// Generated 05-12-2018 07:16:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoTelefono generated by hbm2java
 */
@Entity
@Table(name="TIPO_TELEFONO"
    ,schema="BOLSA_TRABAJO"
)
public class TipoTelefono  implements java.io.Serializable {


     private BigDecimal idTipo;
     private String nombreTipo;
     private Set<Telefono> telefonos = new HashSet<Telefono>(0);

    public TipoTelefono() {
    }

	
    public TipoTelefono(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }
    public TipoTelefono(BigDecimal idTipo, String nombreTipo, Set<Telefono> telefonos) {
       this.idTipo = idTipo;
       this.nombreTipo = nombreTipo;
       this.telefonos = telefonos;
    }
   
     @Id 

    
    @Column(name="ID_TIPO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }

    
    @Column(name="NOMBRE_TIPO", length=100)
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoTelefono")
    public Set<Telefono> getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }




}


