package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoExamen generated by hbm2java
 */
@Entity
@Table(name="TIPO_EXAMEN"
    ,schema="BOLSA_TRABAJO"
)
public class TipoExamen  implements java.io.Serializable {


     private BigDecimal idTipoExamen;
     private String nombreExamen;
     private Set<Examen> examens = new HashSet<Examen>(0);

    public TipoExamen() {
    }

	
    public TipoExamen(BigDecimal idTipoExamen) {
        this.idTipoExamen = idTipoExamen;
    }
    public TipoExamen(BigDecimal idTipoExamen, String nombreExamen, Set<Examen> examens) {
       this.idTipoExamen = idTipoExamen;
       this.nombreExamen = nombreExamen;
       this.examens = examens;
    }
   
     @Id 

    
    @Column(name="ID_TIPO_EXAMEN", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdTipoExamen() {
        return this.idTipoExamen;
    }
    
    public void setIdTipoExamen(BigDecimal idTipoExamen) {
        this.idTipoExamen = idTipoExamen;
    }

    
    @Column(name="NOMBRE_EXAMEN", length=100)
    public String getNombreExamen() {
        return this.nombreExamen;
    }
    
    public void setNombreExamen(String nombreExamen) {
        this.nombreExamen = nombreExamen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoExamen")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }




}


