package Entidad;
// Generated 06-02-2018 04:31:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="USUARIOS"
    ,schema="BOLSA_TRABAJO"
)
public class Usuarios  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private String nombreUsuario;
     private String contrasena;
     private Set<Candidato> candidatos = new HashSet<Candidato>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);
     private Set<Roles> roleses = new HashSet<Roles>(0);

    public Usuarios() {
    }

	
    public Usuarios(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuarios(BigDecimal idUsuario, String nombreUsuario, String contrasena, Set<Candidato> candidatos, Set<Empresa> empresas, Set<Roles> roleses) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.candidatos = candidatos;
       this.empresas = empresas;
       this.roleses = roleses;
    }
   
     @Id 

    
    @Column(name="ID_USUARIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="NOMBRE_USUARIO", length=200)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="CONTRASENA", length=100)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Candidato> getCandidatos() {
        return this.candidatos;
    }
    
    public void setCandidatos(Set<Candidato> candidatos) {
        this.candidatos = candidatos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Roles> getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set<Roles> roleses) {
        this.roleses = roleses;
    }




}


